import { Plus_Jakarta_Sans } from 'next/font/google';
import styles from '../styles/globals.module.scss';
import { GlobalStateProvider } from '@/lib/gobalStateContext';

const font = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalStateProvider>
        <body className={styles.body}>
          <main className={font.className}>{children}</main>
        </body>
      </GlobalStateProvider>
    </html>
  );
}
